/**
 * 扫描 public/images 全部图片尺寸 → 生成 src/data/generated/imageSizes.ts
 *
 * 用途: 修复 CLS (REVIEW_ACTIONS.md P2-10) — unsized-images 根因是大量 <img> 无
 * width/height 属性。运行时组件查表注入宽高, 浏览器可在图片加载前预留布局空间。
 *
 * 支持: WebP (VP8X/VP8/VP8L) / PNG / JPEG(SOF0-SOF15)
 * 无第三方依赖: 直接解析文件头。
 * 运行: npx tsx scripts/scan-image-dimensions.ts
 * 输出 key 形态: "/images/products/product_xxx.webp" (与数据层引用路径一致)
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, relative, sep } from "node:path";

const PUBLIC_DIR = "public/images";
const OUT_FILE = "src/data/generated/imageSizes.ts";

type Dim = [number, number];

function readWebp(buf: Buffer): Dim | null {
  if (buf.length < 30 || buf.toString("ascii", 0, 4) !== "RIFF" || buf.toString("ascii", 8, 12) !== "WEBP") return null;
  // 遍历 RIFF chunk 链, 找到含尺寸信息的第一个帧 chunk
  let pos = 12;
  while (pos + 8 <= buf.length) {
    const fourcc = buf.toString("ascii", pos, pos + 4);
    const size = buf.readUInt32LE(pos + 4);
    const dataStart = pos + 8;
    if (fourcc === "VP8X" && size >= 10 && dataStart + 10 <= buf.length) {
      // flags(1) + reserved(3) + width-1 LE24 + height-1 LE24
      const w = buf.readUIntLE(dataStart + 4, 3) + 1;
      const h = buf.readUIntLE(dataStart + 7, 3) + 1;
      return [w, h];
    }
    if (fourcc === "VP8 " && dataStart + 10 <= buf.length) {
      // 帧头 3B + start code 9D 01 2A + width LE16(&0x3FFF) + height LE16
      if (buf[dataStart + 3] === 0x9d && buf[dataStart + 4] === 0x01 && buf[dataStart + 5] === 0x2a) {
        const w = buf.readUInt16LE(dataStart + 6) & 0x3fff;
        const h = buf.readUInt16LE(dataStart + 8) & 0x3fff;
        return [w, h];
      }
    }
    if (fourcc === "VP8L" && size >= 5 && dataStart + 5 <= buf.length) {
      if (buf[dataStart] === 0x2f) {
        const b1 = buf[dataStart + 1], b2 = buf[dataStart + 2], b3 = buf[dataStart + 3], b4 = buf[dataStart + 4];
        const w = (b1 | ((b2 & 0x3f) << 8)) + 1;
        const h = (((b2 >> 6) & 0x03) | (b3 << 2) | ((b4 & 0x0f) << 10)) + 1;
        return [w, h];
      }
    }
    pos = dataStart + size + (size % 2); // chunks 按 2 字节对齐
  }
  return null;
}

function readPng(buf: Buffer): Dim | null {
  if (buf.length < 24) return null;
  if (buf.readUInt32BE(0) !== 0x89504e47) return null;
  return [buf.readUInt32BE(16), buf.readUInt32BE(20)]; // IHDR width/height
}

function readJpeg(buf: Buffer): Dim | null {
  if (buf.length < 4 || buf[0] !== 0xff || buf[1] !== 0xd8) return null;
  let pos = 2;
  while (pos + 9 <= buf.length) {
    if (buf[pos] !== 0xff) { pos++; continue; }
    const marker = buf[pos + 1];
    if (marker === 0xd8 || (marker >= 0xd0 && marker <= 0xd9)) { pos += 2; continue; } // 无长度段
    const segLen = buf.readUInt16BE(pos + 2);
    // SOF0-SOF15 排除 DHT(C4)/JPG(C8)/DAC(CC)
    if (marker >= 0xc0 && marker <= 0xcf && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc) {
      const h = buf.readUInt16BE(pos + 5);
      const w = buf.readUInt16BE(pos + 7);
      return [w, h];
    }
    pos += 2 + segLen;
  }
  return null;
}

function measure(file: string): Dim | null {
  const buf = readFileSync(file);
  try {
    // 按魔数而非扩展名分派: 项目内存在扩展名与实际格式互换的文件 (旧站抓取遗留,
    // 如 news/205/img-01.jpg 实为 WebP, partner_xinsheng.webp 实为 JPEG)
    if (buf.length >= 12 && buf.toString("ascii", 0, 4) === "RIFF") return readWebp(buf);
    if (buf[0] === 0x89 && buf[1] === 0x50) return readPng(buf);
    if (buf[0] === 0xff && buf[1] === 0xd8) return readJpeg(buf);
  } catch {
    /* fallthrough */
  }
  return null;
}

function walk(dir: string, acc: string[] = []): string[] {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, e.name);
    if (e.isDirectory()) walk(full, acc);
    else if (/\.(webp|png|jpe?g)$/i.test(e.name)) acc.push(full);
  }
  return acc;
}

const files = walk(PUBLIC_DIR);
const entries: Record<string, Dim> = {};
let failed = 0;

for (const f of files) {
  const dim = measure(f);
  if (!dim || !dim[0] || !dim[1]) {
    failed++;
    console.error(`  [FAIL] ${f}`);
    continue;
  }
  // 公开路径: /images/... (posix 分隔符, 与代码内引用一致)
  // 注意: 从 public/ 根取相对路径, 保证 key 以 /images/ 开头与数据层引用完全一致
  const key = "/" + relative("public", f).split(sep).join("/");
  entries[key] = dim;
}

mkdirSync("src/data/generated", { recursive: true });
const lines = Object.keys(entries).sort().map(
  (k) => `  "${k}": [${entries[k][0]}, ${entries[k][1]}],`
);
const out = `/**
 * AUTO-GENERATED by scripts/scan-image-dimensions.ts — DO NOT EDIT MANUALLY.
 * 全站图片尺寸清单 (宽, 高 px), 用于 <img> 注入 width/height 消除 CLS。
 * 新增/替换图片后重跑: npx tsx scripts/scan-image-dimensions.ts
 * 覆盖 ${Object.keys(entries).length} 张图片。
 */
export const IMAGE_SIZES: Record<string, readonly [number, number]> = {
${lines.join("\n")}
};
`;
writeFileSync(OUT_FILE, out);

console.log(`scan-image-dimensions: ${Object.keys(entries).length} ok, ${failed} failed -> ${OUT_FILE}`);
